name: Webdriver IO UI Tests

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    continue-on-error: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.0.0

      - name: Setup Grid
        run: docker-compose up -d

      - name: Install dependencies
        run: npm install --force

      - name: Run Tests
        run: npm run wdio-docker

      - name: Stop the Grid
        run: docker-compose down
